version: '3.9'
services:
  api:
    build: .
    command: npm run dev
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./:/app
    working_dir: /app
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hr_platform
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
